const mongoose = require("mongoose");

const analyticsSchema = new mongoose.Schema({
  user_id: String,
  date: Date,
  study_time: Number, // total minutes evaluated manually or by timer
  completed_tasks: Number,
  focus_score: Number // 1-100 metric generated by completion ratio or manual input
});

module.exports = mongoose.model("Analytics", analyticsSchema);
